# Makefile
#
# Last update : Sat, 06 Jul 2019, 12:13
#
# This file was auto generated by makegen, an automatic makefile generator.
#
# Repository : https://github.com/reinhardlinardi/makegen
# Maintainer : segfault1001

# Compiler

COMPILER := gcc

# Flags

COMPILE_FLAGS := -std=c99 -g -w -fpermissive
LINKING_FLAGS := 

# Source code

SRC_ROOT := src
SRC_DIRS := $(shell find $(SRC_ROOT) -type d)
SRC_FILES := $(shell find $(SRC_ROOT) -name '*.c' -type f)

# Build

OBJ_DIR := bin
EXEC_BINARY_DIR := build
OBJ_FILES := $(addprefix $(OBJ_DIR)/, $(notdir $(patsubst %.c, %.o, $(SRC_FILES))))
EXEC_BINARY_NAME := main
EXEC_BINARY := $(EXEC_BINARY_DIR)/$(EXEC_BINARY_NAME)

# Rules

.PHONY : clean
VPATH = $(SRC_DIRS)

$(EXEC_BINARY): $(OBJ_FILES) | $(EXEC_BINARY_DIR)
	@echo "[94mLinking $@ ...[0m"
	@$(COMPILER) -o $@ $^ $(LINKING_FLAGS)

$(EXEC_BINARY_DIR):
	@mkdir -p $@

$(OBJ_DIR)/%.o: %.c | $(OBJ_DIR)
	@echo "[94mCompiling $< ...[0m"
	@$(COMPILER) -o $@ -c $< $(COMPILE_FLAGS)

$(OBJ_DIR):
	@mkdir -p $@

clean:
	@echo "Cleaning up ..."
	@rm $(EXEC_BINARY) $(OBJ_DIR)/*.o